"""empty message

Revision ID: 14b3ee057f24
Revises:
Create Date: 2026-01-08 18:06:23.990366

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14b3ee057f24"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("genre", sa.String(length=255), nullable=False),
        sa.Column("overview", sa.Text(), nullable=False),
        sa.Column("crew", sa.Text(), nullable=False),
        sa.Column("orig_title", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("orig_lang", sa.String(length=50), nullable=False),
        sa.Column("budget", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("revenue", sa.Float(), nullable=False),
        sa.Column("country", sa.String(length=3), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "date", name="unique_movie_constraint"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movies")
    # ### end Alembic commands ###
